### ISSUE TITLE
Improve Visual Styling

### ISSUE THREAD

**Issue by aidanbdh** [aidanbdh/roadtrip#17]
- [x] Add fonts and backup fonts
- [x] Change rems to px
- [x] Increase right margin of the logo
- [x] Make the desert background constant

- [x] Add pictures in background of recommended items

- [x] Add box behind each menu choice to allow changes in a:hover and a:active

- [x] Fix positioning of recommended boxed when window is resized

**Comment by thebearingedge** [comment]
Use the following document to learn about the visual style of twitter.

https://cdn.cms-twdigitalassets.com/content/dam/brand-twitter/asset-download-zip-files/Twitter_Brand_Guidelines.pdf
